# Generated by Django 5.2.7 on 2025-10-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='enrolled_at',
            new_name='date_enrolled',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='student',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'course')},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='status',
        ),
    ]
