# Generated by Django 5.2.7 on 2025-11-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allow_edits',
            field=models.BooleanField(default=True, help_text='Permitir al alumno editar la entrega después de enviarla.'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora límite de entrega.', null=True),
        ),
    ]
