# Generated by Django 5.2.7 on 2025-11-14 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_quiz_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Desafío de Código', max_length=200)),
                ('description', models.TextField(help_text='La descripción del problema o las instrucciones.')),
                ('starter_code', models.TextField(blank=True, help_text='El código base que el alumno verá en el editor.', null=True)),
                ('solution', models.TextField(blank=True, help_text='La solución óptima (la IA la usará para comparar).', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_challenges', to='api.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
