# Generated by Django 5.2.7 on 2025-11-15 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_codechallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveCodeChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Desafío de Código en Vivo', max_length=200)),
                ('description', models.TextField(help_text='La descripción del problema o las instrucciones.')),
                ('starter_code', models.TextField(blank=True, help_text='El código base que el alumno verá en el editor.', null=True)),
                ('solution', models.TextField(help_text='La solución óptima (la IA la usará para comparar).')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_code_challenges', to='api.course')),
            ],
        ),
    ]
