# Generated by Django 5.2.7 on 2025-11-05 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='estimated_duration',
            field=models.CharField(blank=True, help_text='Ej: Aprox. 3h 30m', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='main_image_url',
            field=models.URLField(blank=True, help_text='URL de la imagen de portada (ej: Unsplash)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Biografía del instructor', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, help_text='Ej: Desarrollador Full-Stack & Experto en IA', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CourseBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(choices=[('video', 'Video'), ('article', 'Artículo'), ('access', 'Acceso'), ('task', 'Tarea'), ('certificate', 'Certificado')], default='article', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_objectives', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.course')),
            ],
        ),
    ]
