# Generated by Django 4.2.26 on 2025-11-20 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_livecodechallenge_course_remove_quiz_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='file_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
