# Generated by Django 5.2.7 on 2025-11-05 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='course',
            field=models.ForeignKey(blank=True, help_text='El curso al que este grupo pertenece, si es un grupo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_group', to='api.course'),
        ),
    ]
