# Generated by Django 5.2.7 on 2025-11-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_conversation_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Texto'), ('CODE', 'Código'), ('IMAGE', 'Imagen'), ('FILE', 'Archivo')], default='TEXT', max_length=10),
        ),
    ]
