# Generated by Django 5.2.7 on 2025-11-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_message_file_name_message_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='file_submission',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=models.TextField(blank=True, help_text='Respuesta de texto (opcional si se envía un archivo)', null=True),
        ),
    ]
