# Generated by Django 5.2.7 on 2025-11-08 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_lessonnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='chat_conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_chat', to='api.conversation'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='live_session_room',
            field=models.CharField(blank=True, help_text='Nombre de la sala para la clase en vivo', max_length=100, null=True),
        ),
    ]
