# Generated by Django 5.2.7 on 2025-11-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_lesson_chat_conversation_lesson_live_session_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience_points',
            field=models.IntegerField(default=0, help_text='XP para la mascota'),
        ),
    ]
