# Generated by Django 5.2.7 on 2025-11-11 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_conversation_last_message_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='last_message',
        ),
    ]
